export const NAME = 'blogPost';

export const GET_BLOG_POST_REQUESTED = `${NAME}/GET_BLOG_POST_REQUESTED`;
export const GET_BLOG_POST_FULFILLED = `${NAME}/GET_BLOG_POST_FULFILLED`;

export const CREATE_BLOG_POST_REQUESTED = `${NAME}/CREATE_BLOG_POST_REQUESTED`;
export const CREATE_BLOG_POST_FULFILLED = `${NAME}/CREATE_BLOG_POST_FULFILLED`;

export const GET_ALL_BLOG_POSTS_REQUESTED = `${NAME}/GET_ALL_BLOG_POSTS_REQUESTED`;
export const GET_ALL_BLOG_POSTS_FULFILLED = `${NAME}/GET_ALL_BLOG_POSTS_FULFILLED`;

export const GET_USER_BLOG_POSTS_REQUESTED = `${NAME}/GET_USER_BLOG_POSTS_REQUESTED`;
export const GET_USER_BLOG_POSTS_FULFILLED = `${NAME}/GET_USER_BLOG_POSTS_FULFILLED`;

export const DELETE_BLOG_POST_REQUESTED = `${NAME}/DELETE_BLOG_POST_REQUESTED`;
export const DELETE_BLOG_POST_FULFILLED = `${NAME}/DELETE_BLOG_POST_FULFILLED`;

export const QUERY_BLOG_POST_REQUESTED = `${NAME}/QUERY_BLOG_POST_REQUESTED`;
export const QUERY_BLOG_POST_FULFILLED = `${NAME}/QUERY_BLOG_POST_FULFILLED`;

export const CREATE_BP_COMMENT_REQUESTED = `${NAME}/CREATE_BP_COMMENT_REQUESTED`;
export const CREATE_BP_COMMENT_FULFILLED = `${NAME}/CREATE_BP_COMMENT_FULFILLED`;

export const DELETE_BP_COMMENT_REQUESTED = `${NAME}/DELETE_BP_COMMENT_REQUESTED`;
export const DELETE_BP_COMMENT_FULFILLED = `${NAME}/DELETE_BP_COMMENT_FULFILLED`;
