export const NAME = 'googleApi';

export const GET_USER_LOCATION_REQUESTED = `${NAME}/GET_USER_LOCATION_REQUESTED`;
export const GET_USER_LOCATION_FULFILLED = `${NAME}/GET_USER_LOCATION_FULFILLED`;

export const SET_USER_LOCATION_REQUESTED = `${NAME}/SET_USER_LOCATION_REQUESTED`;
export const SET_USER_LOCATION_FULFILLED = `${NAME}/SET_USER_LOCATION_FULFILLED`;