export const NAME = 'listing';

export const GET_LISTING_REQUESTED = `${NAME}/GET_LISTING_REQUESTED`;
export const GET_LISTING_FULFILLED = `${NAME}/GET_LISTING_FULFILLED`;

export const CREATE_LISTING_REQUESTED = `${NAME}/CREATE_LISTING_REQUESTED`;
export const CREATE_LISTING_FULFILLED = `${NAME}/CREATE_LISTING_FULFILLED`;

export const GET_ALL_LISTINGS_REQUESTED = `${NAME}/GET_ALL_LISTINGS_REQUESTED`;
export const GET_ALL_LISTINGS_FULFILLED = `${NAME}/GET_ALL_LISTINGS_FULFILLED`;

export const GET_USER_LISTINGS_REQUESTED = `${NAME}/GET_USER_LISTINGS_REQUESTED`;
export const GET_USER_LISTINGS_FULFILLED = `${NAME}/GET_USER_LISTINGS_FULFILLED`;

export const DELETE_LISTING_REQUESTED = `${NAME}/DELETE_LISTING_REQUESTED`;
export const DELETE_LISTING_FULFILLED = `${NAME}/DELETE_LISTING_FULFILLED`;

export const QUERY_LISTING_REQUESTED = `${NAME}/QUERY_LISTING_REQUESTED`;
export const QUERY_LISTING_FULFILLED = `${NAME}/QUERY_LISTING_FULFILLED`;

export const CREATE_L_COMMENT_REQUESTED = `${NAME}/CREATE_L_COMMENT_REQUESTED`;
export const CREATE_L_COMMENT_FULFILLED = `${NAME}/CREATE_L_COMMENT_FULFILLED`;

export const DELETE_L_COMMENT_REQUESTED = `${NAME}/DELETE_L_COMMENT_REQUESTED`;
export const DELETE_L_COMMENT_FULFILLED = `${NAME}/DELETE_L_COMMENT_FULFILLED`;

export const UPDATE_L_REQUESTED = `${NAME}/UPDATE_L_REQUESTED`;
export const UPDATE_L_FULFILLED = `${NAME}/UPDATE_L_FULFILLED`;
