export const NAME = 'listing';

export const GET_LISTING_REQUESTED = `${NAME}/GET_LISTING_REQUESTED`;
export const GET_LISTING_FULFILLED = `${NAME}/GET_LISTING_FULFILLED`;

export const CREATE_LISTING_REQUESTED = `${NAME}/CREATE_LISTING_REQUESTED`;
export const CREATE_LISTING_FULFILLED = `${NAME}/CREATE_LISTING_FULFILLED`;
