export const NAME = 'message';

export const DRAFT_MESSAGE = `${NAME}/DRAFT_MESSAGE`;
export const CLEAR_DRAFT = `${NAME}/CLEAR_DRAFT`;

export const SEND_MESSAGE_REQUESTED = `${NAME}/SEND_MESSAGE_REQUESTED`;
export const SEND_MESSAGE_FULFILLED = `${NAME}/SEND_MESSAGE_FULFILLED`;

export const DELETE_MESSAGE_REQUESTED = `${NAME}/DELETE_MESSAGE_REQUESTED`;
export const DELETE_MESSAGE_FULFILLED = `${NAME}/DELETE_MESSAGE_FULFILLED`;
