export const NAME = 'user';

export const REGISTER_USER_REQUESTED = `${NAME}/REGISTER_USER_REQUESTED`;
export const REGISTER_USER_FULFILLED = `${NAME}/REGISTER_USER_FULFILLED`;

export const LOGIN_USER_REQUESTED = `${NAME}/LOGIN_USER_REQUESTED`;
export const LOGIN_USER_FULFILLED = `${NAME}/LOGIN_USER_FULFILLED`;

export const GET_PROFILE_REQUESTED = `${NAME}/GET_PROFILE_REQUESTED`;
export const GET_PROFILE_FULFILLED = `${NAME}/GET_PROFILE_FULFILLED`;

export const LOGOUT = `${NAME}/LOGOUT`;

export const DELETE_PROFILE = `${NAME}/DELETE_PROFILE`;
