export const NAME = 'user';
export const REGISTER_USER_REQUESTED = `${NAME}/REGISTER_USER_REQUESTED`;
export const REGISTER_USER_FULFILLED = `${NAME}/REGISTER_USER_FULFILLED`;
export const LOGIN_USER_REQUESTED = `${NAME}/LOGIN_USER_REQUESTED`;
export const LOGIN_USER_FULFILLED = `${NAME}/LOGIN_USER_FULFILLED`;
