export const NAME = 'workRequest';

export const GET_WORK_REQUEST_REQUESTED = `${NAME}/GET_WORK_REQUEST_REQUESTED`;
export const GET_WORK_REQUEST_FULFILLED = `${NAME}/GET_WORK_REQUEST_FULFILLED`;

export const CREATE_WORK_REQUEST_REQUESTED = `${NAME}/CREATE_WORK_REQUEST_REQUESTED`;
export const CREATE_WORK_REQUEST_FULFILLED = `${NAME}/CREATE_WORK_REQUEST_FULFILLED`;

export const GET_ALL_WORK_REQUESTS_REQUESTED = `${NAME}/GET_ALL_WORK_REQUESTS_REQUESTED`;
export const GET_ALL_WORK_REQUESTS_FULFILLED = `${NAME}/GET_ALL_WORK_REQUESTS_FULFILLED`;

export const GET_USER_WORK_REQUESTS_REQUESTED = `${NAME}/GET_USER_WORK_REQUESTS_REQUESTED`;
export const GET_USER_WORK_REQUESTS_FULFILLED = `${NAME}/GET_USER_WORK_REQUESTS_FULFILLED`;

export const DELETE_WORK_REQUEST_REQUESTED = `${NAME}/DELETE_WORK_REQUEST_REQUESTED`;
export const DELETE_WORK_REQUEST_FULFILLED = `${NAME}/DELETE_WORK_REQUEST_FULFILLED`;

export const QUERY_WORK_REQUEST_REQUESTED = `${NAME}/QUERY_WORK_REQUEST_REQUESTED`;
export const QUERY_WORK_REQUEST_FULFILLED = `${NAME}/QUERY_WORK_REQUEST_FULFILLED`;

export const CREATE_WR_COMMENT_REQUESTED = `${NAME}/CREATE_WR_COMMENT_REQUESTED`;
export const CREATE_WR_COMMENT_FULFILLED = `${NAME}/CREATE_WR_COMMENT_FULFILLED`;

export const DELETE_WR_COMMENT_REQUESTED = `${NAME}/DELETE_WR_COMMENT_REQUESTED`;
export const DELETE_WR_COMMENT_FULFILLED = `${NAME}/DELETE_WR_COMMENT_FULFILLED`;

export const UPDATE_WR_REQUESTED = `${NAME}/UPDATE_WR_REQUESTED`;
export const UPDATE_WR_FULFILLED = `${NAME}/UPDATE_WR_FULFILLED`;